### PR TITLE
scripts: add bootstrap & run

### PR DESCRIPTION
**Pull request by josephholsten**

### CODE REVIEW

**Comment by damacus** [comment]
Why hide these things in scripts? 👎

**Comment by josephholsten** [comment]
I was using all these scripts while trying to make changes. I could not tell how to perform the standard processes. This created a frustrating first-contributor experience:
- the readme didn’t tell me I needed to init submodules, so when I first ran `Hugo server -ws . ` I just was presented with an empty index
- when I pushed my first pr, it failed linting. I did know there was linting, so this would help me discover it. And I certainly don’t want to remember the flags we use.
- I would have created a deploy script as well, but a) it should only be deployed from CI and b) I’m not sure of how much this would actually reduce cognitive burden, since there are important prereqs like git author config and deploy creds.

**Comment by JohnRoesler** [comment]
End result is similar, but have considered using a `makefile`?

**Comment by damacus** [comment]
The problem with the Makefile and the scripts, is the biggest thing they fix (from what I can see) is the unusual clone behaviour. And you you need to clone before you get the makefile so 🤷‍♂️

**Pull request closed without merging**
